import type { HotspotConfig } from '@/game/types';

export const SCENE_HOTSPOTS: Record<string, HotspotConfig[]> = {
  scene_001: [
    {
      id: 'box',
      label: 'Коробка',
      x: 38,
      y: 58,
      width: 22,
      height: 18,
      action: 'navigate',
      nextScene: 'scene_003',
      animation: 'sway',
    },
    {
      id: 'window',
      label: 'Окно',
      x: 52,
      y: 6,
      width: 38,
      height: 28,
      action: 'dialog',
      dialog: 'За окном — бесконечный неоновый город. Дождь стекает по стеклу.',
    },
    {
      id: 'door',
      label: 'Дверь',
      x: 2,
      y: 18,
      width: 16,
      height: 58,
      action: 'dialog',
      dialog: 'Дверь заперта. Сначала стоит разобраться с коробкой.',
    },
    {
      id: 'lamp',
      label: 'Лампа',
      x: 78,
      y: 10,
      width: 10,
      height: 12,
      shape: 'circle',
      action: 'dialog',
      dialog: 'Лампа мерцает тусклым светом.',
    },
  ],
  scene_003: [
    {
      id: 'robot',
      label: 'Зверёк',
      x: 28,
      y: 32,
      width: 44,
      height: 48,
      action: 'dialog',
      dialog: '«У меня закончилась энергия... Поможешь?»',
    },
    {
      id: 'battery_slot',
      label: 'Батарейный отсек',
      x: 46,
      y: 66,
      width: 14,
      height: 12,
      action: 'navigate',
      nextScene: 'scene_005',
    },
    {
      id: 'power_off',
      label: 'Выключить',
      x: 64,
      y: 52,
      width: 12,
      height: 12,
      shape: 'circle',
      action: 'navigate',
      nextScene: 'scene_004',
    },
    {
      id: 'robot_eyes',
      label: 'Глаза',
      x: 50,
      y: 42,
      width: 14,
      height: 6,
      shape: 'ellipse',
      action: 'dialog',
      dialog: 'Глаза зверька тускло мерцают.',
    },
  ],
  scene_005: [
    {
      id: 'storage_door',
      label: 'Кладовка',
      x: 4,
      y: 22,
      width: 24,
      height: 52,
      action: 'navigate',
      nextScene: 'scene_006',
    },
    {
      id: 'lift_door',
      label: 'Лифт',
      x: 36,
      y: 18,
      width: 26,
      height: 58,
      action: 'navigate',
      nextScene: 'scene_009',
    },
    {
      id: 'basement_door',
      label: 'Подвал',
      x: 70,
      y: 28,
      width: 24,
      height: 48,
      action: 'navigate',
      nextScene: 'scene_010',
    },
  ],
  scene_006: [
    {
      id: 'battery',
      label: 'Батарейка',
      x: 12,
      y: 48,
      width: 20,
      height: 22,
      action: 'navigate',
      nextScene: 'scene_013',
    },
    {
      id: 'bolt',
      label: 'Болт',
      x: 40,
      y: 46,
      width: 20,
      height: 22,
      action: 'navigate',
      nextScene: 'scene_014',
    },
    {
      id: 'cassette',
      label: 'Кассета',
      x: 68,
      y: 48,
      width: 20,
      height: 22,
      action: 'navigate',
      nextScene: 'scene_011',
    },
    {
      id: 'shelf',
      label: 'Полка',
      x: 5,
      y: 20,
      width: 90,
      height: 25,
      action: 'dialog',
      dialog: 'Старые полки. Пыль и запах металла.',
    },
    {
      id: 'storage_exit',
      label: 'Дверь',
      x: 82,
      y: 30,
      width: 14,
      height: 45,
      action: 'navigate',
      nextScene: 'scene_005',
    },
  ],
  scene_009: [
    {
      id: 'floor_1',
      label: '1 этаж',
      x: 38,
      y: 62,
      width: 8,
      height: 8,
      shape: 'circle',
      action: 'navigate',
      nextScene: 'scene_012',
    },
    {
      id: 'floor_5',
      label: '5 этаж',
      x: 50,
      y: 62,
      width: 8,
      height: 8,
      shape: 'circle',
      action: 'navigate',
      nextScene: 'scene_012',
    },
    {
      id: 'floor_12',
      label: '12 этаж',
      x: 62,
      y: 62,
      width: 8,
      height: 8,
      shape: 'circle',
      action: 'navigate',
      nextScene: 'scene_012',
    },
  ],
  scene_013: [
    {
      id: 'return_robot',
      label: 'К зверьку',
      x: 40,
      y: 70,
      width: 20,
      height: 15,
      action: 'navigate',
      nextScene: 'scene_007',
    },
  ],
  scene_014: [
    {
      id: 'return_robot_bolt',
      label: 'К зверьку',
      x: 40,
      y: 70,
      width: 20,
      height: 15,
      action: 'navigate',
      nextScene: 'scene_008',
    },
  ],
};

export function getHotspotsForScene(sceneId: string): HotspotConfig[] {
  return SCENE_HOTSPOTS[sceneId] ?? [];
}
